/*
  Previous - sdlevent.c

  This file is distributed under the GNU General Public License, version 2
  or at your option any later version. Read the file gpl.txt for details.

  This file contains user interface event handling routines.
*/
const char SDLevent_fileid[] = "Previous sdlevent.c";

#include "main.h"
#include "configuration.h"
#include "log.h"
#include "event.h"
#include "timing.h"
#include "keymap.h"
#include "screen.h"
#include "shortcut.h"
#include "sdlgui.h"
#include "sdlkeymap.h"
#include "sdlscreen.h"
#include "sdlstatusbar.h"
#include "dimension.hpp"


static bool bIgnoreNextMouseMotion = false; /* Ignore next mouse motion (needed after SDL_WarpMouse) */

static uint32_t SPECIAL_EVENT;

#ifndef ENABLE_RENDERING_THREAD
/* ----------------------------------------------------------------------- */
/**
 * Save an event and make it available to the emulator thread.
 **/
#define MAX_EVENTS  16
static SDL_Event    mainEvent[MAX_EVENTS];
static SDL_SpinLock mainEventLock;
static int          mainEventWrite;
static int          mainEventRead;
static int          mainEventNext;

/* ----------------------------------------------------------------------- */
/**
 * Initialize event queue.
 **/
void GuiEvent_InitEventQueue(void) {
	mainEventRead = mainEventWrite = 0;
}

/* ----------------------------------------------------------------------- */
/**
 * Save an event. Called from main loop.
 **/
static void GuiEvent_PutEventQueue(SDL_Event* event) {
	if (!bEmulationActive)
		return;

	SDL_AtomicLock(&mainEventLock);
	mainEventNext = mainEventWrite + 1;
	if (mainEventNext >= MAX_EVENTS) {
		mainEventNext = 0;
	}
	if (mainEventNext == mainEventRead) {
		Log_Printf(LOG_WARN, "Events queue overflow!");
	} else {
		mainEvent[mainEventWrite] = *event;
		mainEventWrite = mainEventNext;
	}
	SDL_AtomicUnlock(&mainEventLock);
}

/* ----------------------------------------------------------------------- */
/**
 * Get saved event. Called from emulator thread.
 **/
static bool GuiEvent_GetEventQueue(SDL_Event* event) {
	bool valid = false;

	SDL_AtomicLock(&mainEventLock);
	if (mainEventWrite != mainEventRead) {
		mainEventNext = mainEventRead + 1;
		if (mainEventNext >= MAX_EVENTS) {
			mainEventNext = 0;
		}
		*event = mainEvent[mainEventRead];
		valid = true;
		mainEventRead = mainEventNext;
	}
	SDL_AtomicUnlock(&mainEventLock);

	return valid;
}

void GuiEvent_EventQueueHandler(void) {
	SDL_Event event;

	if (GuiEvent_GetEventQueue(&event)) {
		switch (event.type) {
			case SDL_MOUSEMOTION:
				Keymap_MouseMove(event.motion.xrel, event.motion.yrel);
				break;
			case SDL_MOUSEBUTTONDOWN:
				Keymap_MouseDown(event.button.button == SDL_BUTTON_LEFT);
				break;
			case SDL_MOUSEBUTTONUP:
				Keymap_MouseUp(event.button.button == SDL_BUTTON_LEFT);
				break;
			case SDL_MOUSEWHEEL:
				Keymap_MouseWheel(&event.wheel);
				break;
			case SDL_KEYDOWN:
				Keymap_KeyDown(&event.key.keysym);
				break;
			case SDL_KEYUP:
				Keymap_KeyUp(&event.key.keysym);
				break;
			default:
				break;
		}
	}
}
#endif /* !ENABLE_RENDERING_THREAD */

/* ----------------------------------------------------------------------- */
/**
 * Initialize special event.
 **/
void GuiEvent_InitSpecialEvent(void) {
	SPECIAL_EVENT = SDL_RegisterEvents(1);
}

/* ----------------------------------------------------------------------- */
/**
 * Send special events. Called from emulator threads.
 **/
void GuiEvent_SendSpecialEvent(int type) {
	SDL_Event event;
	event.type = SPECIAL_EVENT;
	event.user.code = type;
	SDL_PushEvent(&event);
}


/* ----------------------------------------------------------------------- */
/**
 * Set flag to ignore the mouse event that is generated by SDL_WarpMouse().
 */
void GuiEvent_WarpMouse(void) {
	bIgnoreNextMouseMotion = true;
}

/* ----------------------------------------------------------------------- */
/**
 * Handle mouse motion event.
 */
static void GuiEvent_HandleMouseMotion(SDL_Event *pEvent) {
	static SDL_Event mouse_event[100];

	int i, nEvents;

	static float fSavedDeltaX = 0.0;
	static float fSavedDeltaY = 0.0;

	float fDeltaX;
	float fDeltaY;
	int   nDeltaX;
	int   nDeltaY;

	float fExp = bGrabMouse ? ConfigureParams.Mouse.fExpSpeedLocked : ConfigureParams.Mouse.fExpSpeedNormal;
	float fLin = bGrabMouse ? ConfigureParams.Mouse.fLinSpeedLocked : ConfigureParams.Mouse.fLinSpeedNormal;

	if (bIgnoreNextMouseMotion) {
		bIgnoreNextMouseMotion = false;
		return;
	}

	nDeltaX = pEvent->motion.xrel;
	nDeltaY = pEvent->motion.yrel;

	/* Get all mouse event to clean the queue and sum them */
	nEvents = SDL_PeepEvents(mouse_event, 100, SDL_GETEVENT, SDL_MOUSEMOTION, SDL_MOUSEMOTION);

	for (i = 0; i < nEvents; i++) {
		nDeltaX += mouse_event[i].motion.xrel;
		nDeltaY += mouse_event[i].motion.yrel;
	}

	if (nDeltaX || nDeltaY) {
		/* Adjust values only if necessary */
		if ((fExp != 1.0) || (fLin != 0.0)) {
			/* Initialize float values from integers */
			fDeltaX = (float)nDeltaX;
			fDeltaY = (float)nDeltaY;

			/* Exponential adjustmend */
			if (fExp != 1.0) {
				fDeltaX = (fDeltaX < 0.0) ? -pow(-fDeltaX, fExp) : pow(fDeltaX, fExp);
				fDeltaY = (fDeltaY < 0.0) ? -pow(-fDeltaY, fExp) : pow(fDeltaY, fExp);
			}

			/* Linear adjustment */
			if (fLin != 1.0) {
				fDeltaX *= fLin;
				fDeltaY *= fLin;
			}

			/* Add residuals */
			if ((fDeltaX < 0.0) == (fSavedDeltaX < 0.0)) {
				fSavedDeltaX += fDeltaX;
			} else {
				fSavedDeltaX  = fDeltaX;
			}
			if ((fDeltaY < 0.0) == (fSavedDeltaY < 0.0)) {
				fSavedDeltaY += fDeltaY;
			} else {
				fSavedDeltaY  = fDeltaY;
			}

			/* Convert to integer and save residuals */
			nDeltaX = (int)fSavedDeltaX;
			nDeltaY = (int)fSavedDeltaY;
			fSavedDeltaX -= (float)nDeltaX;
			fSavedDeltaY -= (float)nDeltaY;
		}

		/* Done */
#ifdef ENABLE_RENDERING_THREAD
		Keymap_MouseMove(nDeltaX, nDeltaY);
#else
		pEvent->motion.xrel = nDeltaX;
		pEvent->motion.yrel = nDeltaY;

		GuiEvent_PutEventQueue(pEvent);
#endif
	}
}

/* ----------------------------------------------------------------------- */
/**
 * Sends key up events for all currently pressed keys.
 */
void GuiEvent_ResetKeys(void) {
	SDL_Event event;

	SDL_ResetKeyboard();

	/* Send magic key sequence to avoid stuck keys */
	event.type                = SDL_KEYDOWN;
	event.key.keysym.scancode = SDL_SCANCODE_LCTRL;
	event.key.keysym.sym      = SDLK_LCTRL;
	event.key.keysym.mod      = KMOD_LCTRL;
	SDL_PushEvent(&event);

	if (ConfigureParams.System.bADB) {
		event.type                = SDL_KEYUP;
		event.key.keysym.scancode = SDL_SCANCODE_LCTRL;
		event.key.keysym.sym      = SDLK_LCTRL;
		event.key.keysym.mod      = KMOD_LCTRL;
		SDL_PushEvent(&event);
	}

	event.type                = SDL_KEYUP;
	event.key.keysym.scancode = SDL_SCANCODE_Q;
	event.key.keysym.sym      = SDLK_q;
	event.key.keysym.mod      = KMOD_NONE;
	SDL_PushEvent(&event);
}

/* ----------------------------------------------------------------------- */
/**
 * Is a shortcut modifier key pressed?
 */
static bool GuiEvent_ShortcutMod(int modkey)
{
	return (modkey & KMOD_CTRL) && (modkey & KMOD_ALT);
}


/* ----------------------------------------------------------------------- */
/**
 * SDL message handler.
 * Here we process the SDL events (keyboard, mouse, ...)
 */
void GuiEvent_EventHandler(void) {
	bool bContinueProcessing;
	SDL_Event event;
	int events;

	do {
		bContinueProcessing = false;

#ifdef ENABLE_RENDERING_THREAD
		if (bEmulationActive) {
			int64_t time_offset = Timing_GetRealTimeOffset() / 1000;
			if (time_offset > 10)
				events = SDL_WaitEventTimeout(&event, (int)time_offset);
			else
				events = SDL_PollEvent(&event);
		} else {
			events = SDL_WaitEvent(&event);
		}
#else
		events = SDL_WaitEventTimeout(&event, 100);
#endif
		if (!events) {
			/* no events -> if emulation is active or
			 * user is quitting -> return from function.
			 */
			continue;
		}
		switch (event.type) {
			case SDL_WINDOWEVENT:
				switch(event.window.event) {
					case SDL_WINDOWEVENT_CLOSE:
						SDL_FlushEvent(SDL_QUIT); /* Remove quit event if pending */
						Main_RequestQuit(true);
						break;
					case SDL_WINDOWEVENT_RESIZED:
						Screen_SizeChanged();
						break;
					default:
						break;
				}
				continue;

			case SDL_QUIT:
				Main_RequestQuit(true);
				break;

			case SDL_MOUSEMOTION:               /* Read/Update internal mouse position */
				GuiEvent_HandleMouseMotion(&event);
				bContinueProcessing = false;
				break;

			case SDL_MOUSEBUTTONDOWN:
				if (ConfigureParams.Mouse.bEnableMacClick) {
					if (event.button.button == SDL_BUTTON_LEFT) {
						if (SDL_GetModState() & KMOD_CTRL) {
							event.button.button = SDL_BUTTON_RIGHT;
						}
					}
				}
				if (event.button.button == SDL_BUTTON_LEFT) {
					if (ConfigureParams.Mouse.bEnableAutoGrab) {
						if (bGrabMouse) {
							if (SDL_GetModState() & KMOD_CTRL) {
								bGrabMouse = false;
								Screen_SetMouseGrab(bGrabMouse);
								break;
							}
						} else {
							bGrabMouse = true;
							Screen_SetMouseGrab(bGrabMouse);
							break;
						}
					}
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseDown(true);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				else if (event.button.button == SDL_BUTTON_RIGHT)
				{
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseDown(false);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				break;

			case SDL_MOUSEBUTTONUP:
				if (ConfigureParams.Mouse.bEnableMacClick) {
					if (event.button.button == SDL_BUTTON_LEFT) {
						if (SDL_GetModState() & KMOD_CTRL) {
							event.button.button = SDL_BUTTON_RIGHT;
						}
					}
				}
				if (event.button.button == SDL_BUTTON_LEFT) {
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseUp(true);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				else if (event.button.button == SDL_BUTTON_RIGHT)
				{
#ifdef ENABLE_RENDERING_THREAD
					Keymap_MouseUp(false);
#else
					GuiEvent_PutEventQueue(&event);
#endif
				}
				break;

			case SDL_MOUSEWHEEL:
#ifdef ENABLE_RENDERING_THREAD
				Keymap_MouseWheel(&event.wheel);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			case SDL_KEYDOWN:
				if (event.key.repeat) {
					break;
				}
				if (ShortCut_CheckKeys(event.key.keysym.sym, GuiEvent_ShortcutMod(event.key.keysym.mod), true)) {
					ShortCut_ActKey();
					break;
				}
#ifdef ENABLE_RENDERING_THREAD
				Keymap_KeyDown(&event.key.keysym);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			case SDL_KEYUP:
				if (ShortCut_CheckKeys(event.key.keysym.sym, GuiEvent_ShortcutMod(event.key.keysym.mod), false)) {
					break;
				}
#ifdef ENABLE_RENDERING_THREAD
				Keymap_KeyUp(&event.key.keysym);
#else
				GuiEvent_PutEventQueue(&event);
#endif
				break;

			default:
				/* check special remote events */
				if (event.type == SPECIAL_EVENT) {
					switch (event.user.code) {
						case EVENT_PAUSE:
							Main_PauseEmulation(false);
							break;
						case EVENT_UNPAUSE:
							Main_UnPauseEmulation();
							break;
#ifndef ENABLE_RENDERING_THREAD
						case EVENT_REPAINT:
							Statusbar_Update(sdlscrn);
							Screen_Repaint();
							break;
						case EVENT_ND_DISPLAY:
							nd_display_repaint();
							break;
						case EVENT_HALT:
							Main_HaltDialog();
							break;
#endif
						default:
							break;
					}
					break;
				}
				/* don't let unknown events delay event processing */
				bContinueProcessing = true;
				break;
		}
	} while (bContinueProcessing || !(bEmulationActive || bQuitProgram));
}


void UI_Init(void) {
#if HAVE_SETENV
	/* Needed on maemo but useful also with normal X11 window managers for
	 * window grouping when you have multiple Previous SDL windows open */
	setenv("SDL_VIDEO_X11_WMCLASS", "previous", 1);
#endif

	/* Init SDL's video subsystem. Note: Audio subsystem
	   will be initialized later (failure not fatal). */
	if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) < 0)
	{
		Main_ErrorExit("Could not initialize the SDL library:", SDL_GetError(), -1);
	}
	SDLGui_Init();
	Screen_Init();
	Keymap_Init();
}

void UI_UnInit(void) {
	SDLGui_UnInit();
	Screen_UnInit();

	/* SDL uninit: */
	SDL_Quit();
}
